import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// src/components/testemunhas.tsx
import { useEffect } from 'react';
import AOS from 'aos';
import 'aos/dist/aos.css';
import testemunha from '../assets/t1.png'; // Imagem de exemplo, substitua pelo caminho correto
const Testemunhas = () => {
    useEffect(() => {
        AOS.init({ duration: 800, easing: 'ease-in-out', once: true });
    }, []);
    return (_jsx("section", { className: "py-5 bg-light", style: { minHeight: '100vh' }, children: _jsxs("div", { className: "container text-center", children: [_jsx("h2", { className: "mb-5", children: "O que nossos clientes dizem" }), _jsxs("div", { className: "row justify-content-center d-flex align-items-center", children: [_jsx("div", { className: "col-md-4 mb-4 d-flex justify-content-center", "data-aos": "fade-up", children: _jsxs("div", { className: "bg-white p-4 rounded shadow-lg", children: [_jsx("p", { className: "text-muted mb-3", children: "\"A Mecs transformou a nossa forma de trabalhar! O site ficou r\u00E1pido, seguro e super f\u00E1cil de navegar.\"" }), _jsxs("div", { className: "d-flex justify-content-center align-items-center", children: [_jsx("img", { src: testemunha, alt: "Testemunha 1", className: "rounded-circle me-3 w-25" }), _jsxs("div", { children: [_jsx("h5", { className: "mb-0", children: "Jo\u00E3o Silva" }), _jsx("p", { className: "text-muted", children: "CEO da Empresa XYZ" })] })] })] }) }), _jsx("div", { className: "col-md-4 mb-4 d-flex justify-content-center", "data-aos": "fade-up", "data-aos-delay": "200", children: _jsxs("div", { className: "bg-white p-4 rounded shadow-lg", children: [_jsx("p", { className: "text-muted mb-3", children: "\"O suporte da equipe foi excepcional. Eles entenderam nossas necessidades e entregaram um trabalho incr\u00EDvel!\"" }), _jsxs("div", { className: "d-flex justify-content-center align-items-center", children: [_jsx("img", { src: testemunha, alt: "Testemunha 2", className: "rounded-circle me-3 w-25" }), _jsxs("div", { children: [_jsx("h5", { className: "mb-0", children: "Maria Oliveira" }), _jsx("p", { className: "text-muted", children: "Fundadora da Startup ABC" })] })] })] }) }), _jsx("div", { className: "col-md-4 mb-4 d-flex justify-content-center", "data-aos": "fade-up", "data-aos-delay": "400", children: _jsxs("div", { className: "bg-white p-4 rounded shadow-lg", children: [_jsx("p", { className: "text-muted mb-3", children: "\"Recomendo a Mecs para todos! A qualidade de trabalho e o atendimento s\u00E3o excepcionais. Meus clientes adoram o novo site!\"" }), _jsxs("div", { className: "d-flex justify-content-center align-items-center", children: [_jsx("img", { src: testemunha, alt: "Testemunha 3", className: "rounded-circle me-3 w-25" }), _jsxs("div", { children: [_jsx("h5", { className: "mb-0", children: "Carlos Mendes" }), _jsx("p", { className: "text-muted", children: "Co-Fundador da Tech Ventures" })] })] })] }) })] })] }) }));
};
export default Testemunhas;
